name: Mirror master to staging

on:
  push:
    branches:
      - master

jobs:
  mirror-master-to-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rebase master branch to staging branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout staging
          git rebase master
          git push origin staging --force

