name: Release

on:
  release:
    types: [published]

jobs:
  mirror-head-to-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rebase main branch to release branch
        run: |
          git config user.name github-actions
          git config github-actions@github.com
          git push origin HEAD:release --force
