name: Release

on:
  release:
    types: [published]

jobs:
  mirror-head-to-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get auto-lr-bot token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.GH_APP_AUTO_LR_BOT_ID }}
          private-key: ${{ secrets.GH_APP_AUTO_LR_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "auto-literature-review"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Rebase main branch to release branch
        run: |
          git push origin HEAD:release --force
